### ISSUE TITLE
Remove Dead Code

### ISSUE THREAD

**Issue by MovGP0** [empira/PDFsharp-1.5#78]
## Expected Behavior

Dead code should be removed from the code. This includes code that is commented using `//` or `#if false` statements, code that is unreachable, code that is not used like `using` statements and `this.XXX` statements, etc. 

## Actual Behavior

Lots of code that is not used at all and wastes lots of valuable develper time. 

## Steps to Reproduce the Behavior

Read the source code. Use Resharper and Roslynator to find code issues.

**Comment by icnocop** [comment]
I also think calls to `Debug.Assert` should be removed/replaced.

When I run PDFSharp built from the `Debug` solution configuration, and `Debug.Assert` is called, an unexpected message box is displayed.

I expected the code to run without user intervention.

Thank you.

**Comment by TH-Soft** [comment]
`Debug.Assert` works as expected and the compiler removes the calls from the Release build.

When you see the message using a Debug build then you can jump into the source code (assuming you run under a debugger) and can check what is going on.

**Comment by icnocop** [comment]
@TH-Soft , you are right.

Sorry, I should have been more specific.

The only `Debug.Assert`s I have "issues" with are the ones like this:
https://github.com/empira/PDFsharp/blob/3205bd933b464d150c0f42e8bcdff3314b6c6164/src/PdfSharp/Pdf/PdfOutline.cs#L375

There are other cases where maybe an exception should be thrown, or a warning message logged, instead of just calling `Debug.Assert`, but that's probably a different topic. 😄

**Comment by ThomasHoevel** [comment]
There are plans to remove obsolete code when PDFsharp 6.0.0 is stable.
